### ISSUE TITLE
Spectral augmentations? 

### ISSUE THREAD

**Issue by mpariente** [facebookresearch/WavAugment#1]
First off, thanks a lot for open-sourcing this tool !
I know the name suggests otherwise but would you consider adding spectral augmentations here?

**Comment by eugene-kharitonov** [comment]
Hello @mpariente and thanks for your interest!

Do you have something specific in mind? Some things, like band-reject, are available now: https://github.com/facebookresearch/WavAugment/blob/master/examples/python/process_file.py#L72-L73

**Comment by mpariente** [comment]
Thanks for your answer !
SpecAugment, phase rotations, elastic deformations for example? 
Spectral transformation could also be regarded as deterministic augmentation, such as STFT, Mel, MFCCs etc..

**Comment by eugene-kharitonov** [comment]
Right :) I guess short-term we are more focused on augmentations that can be performed on the raw waveform...

**Comment by mpariente** [comment]
Thanks for your answer !
