### ISSUE TITLE
Speed Effect Augmentation?

### ISSUE THREAD

**Issue by BilalDendani** [facebookresearch/WavAugment#12]
Hello every one, 
I am asking about applying speed as a speech augmentation technique. Does the source code provide an implementation for this technique. I tried with the command `Sped = augment.EffectChain.speed(100)`, however  an invalid syntax issue. Please, I need an example about speed augmentation if it is implemented in the library. 
Thank you.

**Comment by haoheliu** [comment]
Hi,

I tried the speed effect too and it works well. I guess there is some kind of limit for the parameter. Maybe the one you use is too large for the speed function. You can try:

augment.EffectChain.speed(1.5)
augment.EffectChain.speed(2)

Thank you.

**Comment by haoheliu** [comment]
> Hello every one,
> I am asking about applying speed as a speech augmentation technique. Does the source code provide an implementation for this technique. I tried with the command `Sped = augment.EffectChain.speed(100)`, however an invalid syntax issue. Please, I need an example about speed augmentation if it is implemented in the library.
> Thank you.

Also, I find 'tempo' have a better speeding effect than 'speed'

**Comment by BilalDendani** [comment]
Thank you for your answer @haoheliu. However, the error still remains when launching the commands `augment.EffectChain.speed(1.5)`
`augment.EffectChain.speed(2)`
The error is  AttributeError: 'float' object has no attribute '_append_effect_to_chain' when executing `augment.EffectChain.speed(1.5)`

**Comment by haoheliu** [comment]
> Thank you for your answer @haoheliu. However, the error still remains when launching the commands `augment.EffectChain.speed(1.5)`
> `augment.EffectChain.speed(2)`
> The error is AttributeError: 'float' object has no attribute '_append_effect_to_chain' when executing `augment.EffectChain.speed(1.5)`

Sorry I cannot reproduce this errors. The following code works fine for me. You can try them in [colab](https://colab.research.google.com/github/facebookresearch/WavAugment/blob/master/examples/python/WavAugment_walkthrough.ipynb#scrollTo=S7UgybVYT2St):

```python
y = augment.EffectChain().speed(1.5).rate(16000)
y = y.apply(x, src_info={'rate': sr})
ipd.Audio(y, rate=sr)

y = augment.EffectChain().speed(1.5) # have no effect, but also have no error
y = y.apply(x, src_info={'rate': sr})
ipd.Audio(y, rate=sr)

y = augment.EffectChain().tempo(1.5)
y = y.apply(x, src_info={'rate': sr})
ipd.Audio(y, rate=sr)
```

**Comment by haoheliu** [comment]
> Thank you for your answer @haoheliu. However, the error still remains when launching the commands `augment.EffectChain.speed(1.5)`
> `augment.EffectChain.speed(2)`
> The error is AttributeError: 'float' object has no attribute '_append_effect_to_chain' when executing `augment.EffectChain.speed(1.5)`

Hey, I got it. You miss the brackets after the "EffectChain".

**Comment by eugene-kharitonov** [comment]
@haoheliu thanks for the help! @BilalDendani - does this solve your issue?

**Comment by BilalDendani** [comment]
Thanks @eugene-kharitonov and @haoheliu. I missed the two brackets after EffectChain method like suggested by @haoheliu.
Issue solved.
Thank you so much.
