### ISSUE TITLE
making non-native like speech using WavAugment?

### ISSUE THREAD

**Issue by BilalDendani** [facebookresearch/WavAugment#17]
Hello everyone, 
I am asking if is it possible to use WavAugment effect to make like non-native speech data by augmenting native ones.
If yes, which technique can be used to effect native speech to be like non-native. 
Thank you.

**Comment by eugene-kharitonov** [comment]
Hey,

Thanks for the issue. I think this goes really beyond the score of WavAugment; we only deal with pretty low-level augmentations.
